package errors

import (
	"encoding/json"
	"strings"
	"testing"
)

// The codes the specification promises. errors.md may add codes; it may not lack one of these.
var specified = strings.Fields(`
AUTH_REQUIRED TOKEN_EXPIRED TOKEN_REVOKED TOKEN_SCOPE BUSINESS_NOT_IN_LOGIN TOKEN_SIGNATURE FORBIDDEN_ROLE AGENT_CATEGORY AGENT_PAUSED REAUTH_REQUIRED
PASSKEY_REQUIRED SSO_REQUIRED
ORG_PENDING_LIMIT ORG_FROZEN ORG_STATUS_REFUSED ADDRESS_BLOCKED ORG_UNDER_REVIEW ACCOUNT_LAST_OWNER PLAN_LIMIT_APPS FREE_APP_TAKEN PLAN_LIMIT_MEMBERS PLAN_LIMIT_PREVIEWS PLAN_LIMIT_EMAIL_DOMAINS PRODUCTION_NEEDS_MAIN PREVIEW_NO_WORKFLOWS PLAN_LIMIT_RUNS PLAN_DOWNGRADE_BLOCKED PLAN_FEATURE PROMOTE_UNAVAILABLE PROMOTED_ONLY TRIAL_USED
DEMO_NOT_FOUND DEMO_CLAIMED DEMO_WRONG_DOMAIN DEMO_UNCLAIMED HANDOVER_WRONG_EMAIL PAYOUTS_UNAVAILABLE
MANIFEST_INVALID MANIFEST_UNKNOWN_KEY CONVENTIONS_VERSION_UNSUPPORTED DOCTOR_FAILED
SECRET_IN_COMMIT SECRET_VALUE_NEEDS_HUMAN SECRET_SHREDDED SECRET_UNSET SECRET_SHARED_EXISTS SECRET_TOO_SHORT
GRANT_NEEDED CONFIRMATION_NEEDED CONNECTION_CALLER_UNKNOWN CONNECTION_UNKNOWN CONNECTION_NOT_GRANTED CONNECTION_PAUSED CONNECTION_REVOKED CONNECTION_LIMIT CONNECTION_SECRET_UNSET CONNECTION_TOKEN_FAILED CONNECTION_UPSTREAM CONNECTION_UNCONFIRMED CONNECTION_REQUEST_AMBIGUOUS CONNECTION_BUSY
BUILD_FAILED BUILD_TIMEOUT IMAGE_PULL_FAILED SECRET_IN_IMAGE SOURCE_MAPS_PUBLISHED
HEALTH_CHECK_FAILED CONTAINER_CRASHED FUNCTIONS_NOT_REGISTERED MIGRATE_FAILED DEPLOY_CANCELLED DEPLOY_IN_PROGRESS NEEDS_DEPLOY PLATFORM_DEPLOY_FAILED DEPLOY_FAILED
PACKAGE_MALICIOUS PACKAGE_LOOKALIKE
CSRF_REJECTED PATH_AMBIGUOUS CHALLENGE_REQUIRED CDN_ORIGIN_REQUIRED RATE_LIMITED BODY_TOO_LARGE
WEBHOOK_UNVERIFIED WEBHOOK_SOURCE_UNKNOWN WEBHOOK_DEAD DELIVERY_UNVERIFIED
INBOX_NOT_DECLARED INBOX_DOMAIN_TAKEN INBOX_UNAVAILABLE INBOX_MESSAGE_DROPPED DEV_NOT_RUNNING
RUN_PARKED RUN_STEP_LIMIT RUN_CONCURRENCY_LIMIT RUN_STEP_FAILED RUN_FAILED RUN_APP_UNREACHABLE PLATFORM_RUN_INTERRUPTED EVENT_RATE_LIMITED GRAPH_DRIFT INVOKE_FOREIGN FUNCTION_NOT_LIVE APP_NOT_LIVE
DOMAIN_UNVERIFIED DOMAIN_TAKEN DOMAIN_ADDED_BY_TEAM PLAN_LIMIT_DOMAINS ORG_DOMAIN_EXISTS SSO_DOMAIN_UNVERIFIED EMAIL_DOMAIN_UNVERIFIED EMAIL_PAUSED EMAIL_RATE_LIMITED EMAIL_LINK_BLOCKED
EMAIL_ATTACHMENT_INVALID EMAIL_ATTACHMENT_TOO_LARGE EMAIL_ATTACHMENT_BLOCKED EMAIL_ATTACHMENT_NOT_FOUND
EMAIL_SENDER_INVALID STRIPE_KEY_INVALID STRIPE_ACCOUNT_IN_USE CDN_UNAVAILABLE CDN_KEY_INVALID CDN_IN_USE
GITHUB_NOT_SET_UP GITHUB_NOT_INSTALLED GITHUB_INSTALLATION_UNVERIFIED GITHUB_INSTALLATION_TAKEN GITHUB_REPO_UNAVAILABLE GITHUB_REPO_TAKEN GITHUB_REPO_NOT_EMPTY
LOG_DESTINATION_FAILED STORAGE_QUOTA BUCKET_UNREACHABLE UPLOAD_TOO_LARGE OBJECT_QUARANTINED MEDIA_NOT_READY IMAGE_NOT_READY IMAGE_UNREADABLE NOT_AN_IMAGE MEDIA_LINK_EXPIRED MEDIA_LINK_INVALID
EXPORT_IN_PROGRESS EXPORT_FAILED RESTORE_NOT_AVAILABLE RESTORE_IN_PROGRESS APP_NOT_RESTORABLE RESTORE_POINT_NOT_ARCHIVED DB_ACCESS_OFF CONFIRM_REQUIRED CONFIRM_INVALID CONFIRM_CHANGED QUERY_FAILED QUERY_RESULT_TOO_LARGE QUERY_BUSY DB_URL_PRIVATE
RESOURCE_TAKEN EMAIL_DOMAIN_TAKEN RESOURCES_NOT_RELEASED
PLATFORM_UNAVAILABLE NODE_DOWN NODE_DRAIN_NO_TARGET NODE_DRAIN_NO_COPY
LICENCE_MISSING LICENCE_INVALID LICENCE_EXPIRED SUPPORT_DOOR_CLOSED SUPPORT_DOOR_TIMEOUT RELEASE_NOT_COVERED PACKAGE_CHECK_OFF
REPO_TOO_LARGE SOURCE_CHANGED INVALID_REQUEST CONFLICT NOT_FOUND NEEDS_HUMAN UPDATE_FAILED GIT_TLS_UNTRUSTED UNKNOWN_COMMAND POLICY_APPLY_FAILED
CLI_ERROR LOCAL_DOCKER_UNAVAILABLE DEV_STACK_FAILED WAKE_FAILED FORBIDDEN
INIT_NO_TOKEN TOKEN_INVALID TOKEN_ALREADY_USED UPSTREAM_UNAVAILABLE
INIT_CONFIG INIT_PROCESS INIT_EXEC INIT_SECRETS INIT_SECRET_FILES APP_OUT_OF_MEMORY APP_MEMORY_HIGH APP_CPU_SLEEP
DISK_CRITICAL POSTGRES_DOWN IMAGE_NO_COMMAND COMMAND_NOT_RUNNABLE CONTAINER_START_FAILED CONTAINER_NOT_FOUND TOKEN_MALFORMED WAKE_TIMEOUT FREE_CAPACITY_BUSY INVALID_ARGUMENT DATABASE_FAILED DATABASE_CREDENTIALS_REJECTED RESTORE_FAILED NODE_STATE_FAILED DOCKER_FAILED
DATABASE_MOVE_FAILED COPY_UNAVAILABLE COPY_BEHIND COPY_VERSION_MISMATCH
CONTROL_PLANE_SUPERSEDED ROLLBACK_UNAVAILABLE
APP_MANAGED APP_PAUSED MANAGED_UNAVAILABLE MANAGED_NO_RELEASE MANAGED_LINK_TAKEN MANAGED_SOURCE_IN_USE
SEARCH_KEY_INVALID SEARCH_KEY_REJECTED SEARCH_ACCESS_DENIED SEARCH_API_DISABLED SEARCH_UNAVAILABLE
`)

func TestEveryCodeDocumented(t *testing.T) {
	for _, code := range specified {
		e, ok := Lookup(code)
		if !ok {
			t.Errorf("%s: no section in errors.md", code)
			continue
		}
		if e.Fix == "" || e.When == "" || len(e.Surfaces) == 0 {
			t.Errorf("%s: section needs Status, Surface, When and Fix lines: %+v", code, e)
		}
		if e.Example == "" {
			t.Errorf("%s: no example", code)
			continue
		}
		var b Body
		if err := json.Unmarshal([]byte(e.Example), &b); err != nil {
			t.Errorf("%s: example is not valid JSON: %v", code, err)
			continue
		}
		if b.Error.Code != code {
			t.Errorf("%s: example carries code %s", code, b.Error.Code)
		}
		if b.Error.Docs != DocsBase+code {
			t.Errorf("%s: example docs URL is %s", code, b.Error.Docs)
		}
		if b.Error.Message == "" || b.Error.Fix == "" {
			t.Errorf("%s: example needs message and fix", code)
		}
	}
	for _, code := range Codes() {
		if !contains(specified, code) {
			t.Errorf("%s: documented in errors.md but not in the specified list; add it to the test and CONTRACT.md §10", code)
		}
	}
}

func TestNewDefaultsFromCatalogue(t *testing.T) {
	b := New("AUTH_REQUIRED", "", "", map[string]any{"route": "/x"})
	if b.Error.Fix == "" || b.Error.Message == "" || b.Error.Docs != DocsBase+"AUTH_REQUIRED" {
		t.Fatalf("New did not fill from the catalogue: %+v", b)
	}
	if !strings.Contains(string(b.JSON()), `"route":"/x"`) {
		t.Fatal("details missing from JSON")
	}
}

func contains(list []string, s string) bool {
	for _, x := range list {
		if x == s {
			return true
		}
	}
	return false
}
