// Package dev is `whisk dev`: the stub from the contract with Postgres, PgBouncer, the Inngest
// dev server and, when the manifest asks, Valkey and object storage managed through Docker
// Compose in .whisk/dev/. Planning is pure; the shell runs docker and the stub.
package dev

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/whisk-run/contract/manifest"
)

// Images pinned for the local stack.
const (
	imagePostgres  = "postgres:18-alpine"
	imagePgBouncer = "edoburu/pgbouncer:v1.26.0-p0"
	imageInngest   = "inngest/inngest:v1.46.0"
	imageValkey    = "valkey/valkey:9.1.2-alpine"
	imageStorage   = "rustfs/rustfs:1.0.1"
)

// Ports are the host ports the stack publishes on 127.0.0.1.
type Ports struct {
	Postgres  int
	PgBouncer int
	Inngest   int
	Valkey    int
	Storage   int
	Console   int
}

// Plan is everything derived from the manifest and the chosen ports.
type Plan struct {
	Project     string // compose project name
	Database    string // database name
	Compose     string // the compose file
	DatabaseURL string // through PgBouncer, what the app receives
	DirectURL   string // straight to Postgres, for psql and migrations that need it
	InngestURL  string
	ExtraEnv    []string // WHISK_KV_URL, WHISK_STORAGE_* when declared
	HostNetwork bool
}

// BuildPlan derives the local stack for a manifest. internalPort is the stub's internal
// listener, which the dev server calls back; hostNetwork is true on Linux without Docker
// Desktop, where a container reaches the host only through host networking.
func BuildPlan(m manifest.Manifest, ports Ports, internalPort int, hostNetwork bool) Plan {
	db := dbName(m.Name)
	p := Plan{
		Project:     "whisk-" + m.Name,
		Database:    db,
		DatabaseURL: fmt.Sprintf("postgres://whisk:whisk@127.0.0.1:%d/%s?sslmode=disable", ports.PgBouncer, db),
		DirectURL:   fmt.Sprintf("postgres://whisk:whisk@127.0.0.1:%d/%s?sslmode=disable", ports.Postgres, db),
		InngestURL:  fmt.Sprintf("http://127.0.0.1:%d", ports.Inngest),
		HostNetwork: hostNetwork,
	}
	if m.KV {
		p.ExtraEnv = append(p.ExtraEnv, fmt.Sprintf("WHISK_KV_URL=redis://127.0.0.1:%d/0", ports.Valkey))
	}
	if m.Storage {
		p.ExtraEnv = append(p.ExtraEnv,
			fmt.Sprintf("WHISK_STORAGE_ENDPOINT=http://127.0.0.1:%d", ports.Storage),
			"WHISK_STORAGE_BUCKET=whisk",
			"WHISK_STORAGE_ACCESS_KEY=whisk",
			"WHISK_STORAGE_SECRET_KEY=whiskwhisk",
			"WHISK_STORAGE_PREFIX="+m.Name+"/",
			"WHISK_STORAGE_REGION=local",
		)
	}
	p.Compose = composeYAML(m, ports, internalPort, hostNetwork, db)
	return p
}

func dbName(app string) string { return strings.ReplaceAll(app, "-", "_") }

// Hash identifies the inputs a compose file was generated from, so a changed manifest or
// port set regenerates it and an unchanged one is reused while the stack runs.
func Hash(m manifest.Manifest, ports Ports, internalPort int) string {
	sum := sha256.Sum256([]byte(fmt.Sprintf("%s|%v|%v|%v|%d", m.Name, m.KV, m.Storage, ports, internalPort)))
	return hex.EncodeToString(sum[:8])
}

func composeYAML(m manifest.Manifest, ports Ports, internalPort int, hostNetwork bool, db string) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	w("# Generated by whisk dev for %s from whisk.yaml; edit the manifest, not this file.", m.Name)
	w("# inputs: %s", Hash(m, ports, internalPort))
	w("name: whisk-%s", m.Name)
	w("services:")
	w("  postgres:")
	w("    image: %s", imagePostgres)
	w("    environment: {POSTGRES_USER: whisk, POSTGRES_PASSWORD: whisk, POSTGRES_DB: %s}", db)
	w(`    ports: ["127.0.0.1:%d:5432"]`, ports.Postgres)
	w(`    volumes: ["postgres:/var/lib/postgresql"]`)
	w(`    healthcheck: {test: ["CMD-SHELL", "pg_isready -U whisk -d %s"], interval: 2s, timeout: 3s, retries: 30}`, db)
	w("  pgbouncer:")
	w("    image: %s", imagePgBouncer)
	w("    environment:")
	w("      DB_HOST: postgres")
	w("      DB_USER: whisk")
	w("      DB_PASSWORD: whisk")
	w("      DB_NAME: %s", db)
	w("      POOL_MODE: transaction")
	w("      AUTH_TYPE: scram-sha-256")
	w("      MAX_CLIENT_CONN: \"200\"")
	w("      DEFAULT_POOL_SIZE: \"20\"")
	w(`    ports: ["127.0.0.1:%d:5432"]`, ports.PgBouncer)
	w("    depends_on: {postgres: {condition: service_healthy}}")
	w("  inngest:")
	w("    image: %s", imageInngest)
	callback := fmt.Sprintf("http://host.docker.internal:%d%s", internalPort, m.Queue.Endpoint)
	if hostNetwork {
		callback = fmt.Sprintf("http://127.0.0.1:%d%s", internalPort, m.Queue.Endpoint)
		w(`    command: ["inngest", "dev", "-u", %s, "--no-discovery", "--host", "127.0.0.1", "--port", "%d"]`, yamlString(callback), ports.Inngest)
		w("    network_mode: host")
	} else {
		w(`    command: ["inngest", "dev", "-u", %s, "--no-discovery", "--host", "0.0.0.0", "--port", "8288"]`, yamlString(callback))
		w(`    ports: ["127.0.0.1:%d:8288"]`, ports.Inngest)
		w(`    extra_hosts: ["host.docker.internal:host-gateway"]`)
	}
	if m.KV {
		w("  valkey:")
		w("    image: %s", imageValkey)
		w(`    ports: ["127.0.0.1:%d:6379"]`, ports.Valkey)
		w(`    volumes: ["valkey:/data"]`)
	}
	if m.Storage {
		w("  storage:")
		w("    image: %s", imageStorage)
		w("    environment: {RUSTFS_ACCESS_KEY: whisk, RUSTFS_SECRET_KEY: whiskwhisk, RUSTFS_VOLUMES: /data, RUSTFS_CONSOLE_ENABLE: \"true\"}")
		w(`    ports: ["127.0.0.1:%d:9000", "127.0.0.1:%d:9001"]`, ports.Storage, ports.Console)
		w(`    volumes: ["storage:/data"]`)
		w(`    healthcheck: {test: ["CMD-SHELL", "curl -sf http://127.0.0.1:9000/health >/dev/null"], interval: 2s, timeout: 3s, retries: 30}`)
		// The bucket, made with a signed PUT from the store's own image: 200 when made, 409 when
		// it already exists.
		w("  storage-init:")
		w("    image: %s", imageStorage)
		w("    depends_on: {storage: {condition: service_healthy}}")
		w("    environment: {RUSTFS_ACCESS_KEY: whisk, RUSTFS_SECRET_KEY: whiskwhisk}")
		w(`    entrypoint: ["sh", "-c", "code=$$(curl -s -o /dev/null -w '%%{http_code}' --aws-sigv4 aws:amz:local:s3 --user \"$$RUSTFS_ACCESS_KEY:$$RUSTFS_SECRET_KEY\" -X PUT http://storage:9000/whisk); case $$code in 200|409) ;; *) echo \"creating the bucket failed: HTTP $$code\" >&2; exit 1 ;; esac"]`)
	}
	w("volumes:")
	w("  postgres: {}")
	if m.KV {
		w("  valkey: {}")
	}
	if m.Storage {
		w("  storage: {}")
	}
	return b.String()
}

// yamlString quotes s for a YAML flow sequence: JSON's quoting is valid YAML, so a quote in the
// manifest's queue.endpoint stays inside the one argument instead of starting another. JSON
// leaves DEL, the C1 controls and U+FFFE/U+FFFF raw, which YAML refuses, so they are escaped;
// "$" is doubled because Compose would otherwise interpolate a variable there.
func yamlString(s string) string {
	b, _ := json.Marshal(s)
	var out strings.Builder
	for _, r := range string(b) {
		switch {
		case r == '$':
			out.WriteString("$$")
		case r == 0x7f || (r >= 0x80 && r <= 0x9f) || r == 0xfffe || r == 0xffff:
			fmt.Fprintf(&out, `\u%04x`, r)
		default:
			out.WriteRune(r)
		}
	}
	return out.String()
}
